"""create_positions_table

Revision ID: 19fb6bde20b5
Revises: 604d6611e686
Create Date: 2026-01-23 14:43:37.048944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19fb6bde20b5'
down_revision: Union[str, Sequence[str], None] = '604d6611e686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'positions',
        sa.Column('id', sa.Integer(), primary_key=True, index=True, nullable=False),
        sa.Column('tag', sa.String(length=50), unique=True, index=True, nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    # ### end Alembic commands ###
